name: dart_luajit_ffi
description: dart use ffi call lua5.4
version: 0.1.0
repository: https://github.com/Hedwig7s/dart_luajit_ffi
environment:
    sdk: '>=3.8.0 <4.0.0'

dev_dependencies:
    ffigen: ^19.1.0
    lints: ^6.0.0
    test: ^1.16.0
dependencies:
    ffi: ^2.1.4
ffigen:
    output: "lib/generated_bindings.dart"
    headers:
        entry-points:
            - "c_header/lauxlib.h"
            - "c_header/lua.h"
            - "c_header/lualib.h"
    name: LuaFFIBind
    compiler-opts:
        - '-I/usr/include'
        - '-I/usr/lib/clang/20/include'